CREATE TABLE [dbo].[PartAttribute]
(
	[Id] INT NOT NULL CONSTRAINT PK_PartAttribute PRIMARY KEY IDENTITY(10000,1), 
    [Name] NVARCHAR(50) NULL, 
    [Value] NVARCHAR(150) NULL,
    [PartId] INT NOT NULL,
    [GuidId] UNIQUEIDENTIFIER DEFAULT NEWID(), 
    CONSTRAINT [FK_PartAttribute_Part] FOREIGN KEY ([PartId]) REFERENCES [Part]([Id]) ON DELETE CASCADE
)
GO
CREATE NONCLUSTERED INDEX IDX_PartAttribute_GuidId ON [dbo].[PartAttribute] ([GuidId]);