//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bintainer.SharedResources.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bintainer.SharedResources.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical log test message.
        /// </summary>
        public static string CriticalLogTestMessage {
            get {
                return ResourceManager.GetString("CriticalLogTestMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug log test message.
        /// </summary>
        public static string DebugLogTestMessage {
            get {
                return ResourceManager.GetString("DebugLogTestMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bin is required to insert part into subspace..
        /// </summary>
        public static string ErrorBinCannotBeNull {
            get {
                return ResourceManager.GetString("ErrorBinCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A bin must be specified to insert a part into the subspace..
        /// </summary>
        public static string ErrorBinNotSpecified {
            get {
                return ResourceManager.GetString("ErrorBinNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to distribute quantity across subspaces as the specified bin or its associated section is missing or invalid..
        /// </summary>
        public static string ErrorBinOrSectionUnavailable {
            get {
                return ResourceManager.GetString("ErrorBinOrSectionUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to remove attribute template..
        /// </summary>
        public static string ErrorFailedAttributeTemplatedRemove {
            get {
                return ResourceManager.GetString("ErrorFailedAttributeTemplatedRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load part..
        /// </summary>
        public static string ErrorFailedPartLoading {
            get {
                return ResourceManager.GetString("ErrorFailedPartLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed saving part categories..
        /// </summary>
        public static string ErrorFailedSavingPartCategories {
            get {
                return ResourceManager.GetString("ErrorFailedSavingPartCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load part names..
        /// </summary>
        public static string ErrorFailedToLoadPartNames {
            get {
                return ResourceManager.GetString("ErrorFailedToLoadPartNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrive part attributes..
        /// </summary>
        public static string ErrorFailToRetriveAttributes {
            get {
                return ResourceManager.GetString("ErrorFailToRetriveAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified part cannot be arranged due to invalid details..
        /// </summary>
        public static string ErrorInvalidPartDetails {
            get {
                return ResourceManager.GetString("ErrorInvalidPartDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid search parameters..
        /// </summary>
        public static string ErrorInvalidSearchParameter {
            get {
                return ResourceManager.GetString("ErrorInvalidSearchParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory section is missing..
        /// </summary>
        public static string ErrorInventorySectionMissing {
            get {
                return ResourceManager.GetString("ErrorInventorySectionMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error log test message.
        /// </summary>
        public static string ErrorLogTestMessage {
            get {
                return ResourceManager.GetString("ErrorLogTestMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model validation failed at {DateTime} on {Page}. Errors: {Errors}.
        /// </summary>
        public static string ErrorModelState {
            get {
                return ResourceManager.GetString("ErrorModelState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some fields contain invalid data..
        /// </summary>
        public static string ErrorModelStateError {
            get {
                return ResourceManager.GetString("ErrorModelStateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The part is already present..
        /// </summary>
        public static string ErrorPartAlreadyExists {
            get {
                return ResourceManager.GetString("ErrorPartAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The part is missing..
        /// </summary>
        public static string ErrorPartMissing {
            get {
                return ResourceManager.GetString("ErrorPartMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity of items used must be less than the available stock..
        /// </summary>
        public static string ErrorQuantityExceedsStock {
            get {
                return ResourceManager.GetString("ErrorQuantityExceedsStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not load the part attributes..
        /// </summary>
        public static string ErrorRetriveAttributes {
            get {
                return ResourceManager.GetString("ErrorRetriveAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not insert element into subspace..
        /// </summary>
        public static string ErrorSubspaceInsertionFailed {
            get {
                return ResourceManager.GetString("ErrorSubspaceInsertionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used items cannot exceed available quantity..
        /// </summary>
        public static string ErrorUsedItemsExceedAvailable {
            get {
                return ResourceManager.GetString("ErrorUsedItemsExceedAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The subspace count defined for the section &apos;{sectionName}&apos; cannot be zero..
        /// </summary>
        public static string ErrorZeroSubspaceCount {
            get {
                return ResourceManager.GetString("ErrorZeroSubspaceCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute template removed successfully..
        /// </summary>
        public static string InfoAttributeTemplatedRemoved {
            get {
                return ResourceManager.GetString("InfoAttributeTemplatedRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part has been successfully created..
        /// </summary>
        public static string InfoPartCreatedSuccessfully {
            get {
                return ResourceManager.GetString("InfoPartCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository creation or update completed successfully..
        /// </summary>
        public static string InfoRepositoryCreateOrUpdateSuccess {
            get {
                return ResourceManager.GetString("InfoRepositoryCreateOrUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information log test message.
        /// </summary>
        public static string InformationLogTestMessage {
            get {
                return ResourceManager.GetString("InformationLogTestMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trace log test message.
        /// </summary>
        public static string TraceLogTestMessage {
            get {
                return ResourceManager.GetString("TraceLogTestMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to identify the signed-in user..
        /// </summary>
        public static string WarningInvalidUser {
            get {
                return ResourceManager.GetString("WarningInvalidUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory does not exist..
        /// </summary>
        public static string WarningInventoryNotExist {
            get {
                return ResourceManager.GetString("WarningInventoryNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning log test message..
        /// </summary>
        public static string WarningLogTestMessage {
            get {
                return ResourceManager.GetString("WarningLogTestMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results found..
        /// </summary>
        public static string WarningNotFound {
            get {
                return ResourceManager.GetString("WarningNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning part not found..
        /// </summary>
        public static string WarningPartNotFound {
            get {
                return ResourceManager.GetString("WarningPartNotFound", resourceCulture);
            }
        }
    }
}
